import { isUUID } from "./uuid";
import { randomUUID } from "crypto";

describe("isUUID", () => {
  it("should return true for a valid UUID generated by crypto", () => {
    const validUUID = randomUUID();
    expect(isUUID(validUUID)).toBe(true);
  });

  it("should return true for another valid UUID", () => {
    const validUUID = "123e4567-e89b-12d3-a456-426614174000";
    expect(isUUID(validUUID)).toBe(true);
  });

  it("should return false for an invalid UUID", () => {
    const invalidUUID = "not-a-uuid";
    expect(isUUID(invalidUUID)).toBe(false);
  });

  it("should return false for an empty string", () => {
    expect(isUUID("")).toBe(false);
  });

  it("should return false for a string that is almost a UUID", () => {
    const almostUUID = "a1b2c3d4-e5f6-7890-1234-567890abcde"; // one char missing
    expect(isUUID(almostUUID)).toBe(false);
  });

  it("should return false for a non-string value", () => {
    expect(isUUID(null as any)).toBe(false);
    expect(isUUID(undefined as any)).toBe(false);
    expect(isUUID(123 as any)).toBe(false);
    expect(isUUID({} as any)).toBe(false);
    expect(isUUID([] as any)).toBe(false);
  });
});
