export enum DocumentNodeType {
  DOCUMENT = 'document',
  TITLE = 'title',
  SUBTITLE = 'subtitle',
  SECTION = 'section',
  PARAGRAPH = 'paragraph',
  LIST = 'list',
  LIST_ITEM = 'list-item',
  TABLE = 'table',
  TABLE_ROW = 'table-row',
  TABLE_CELL = 'table-cell',
  IMAGE = 'image',
  CAPTION = 'caption',
  CODE = 'code',
  QUOTE = 'quote',
  HEADER = 'header',
  FOOTER = 'footer',
  PAGE_BREAK = 'page-break',
  UNKNOWN = 'unknown'
}
