/**
 * @file Contains functions for generating an OpenAPI (Swagger) specification file.
 */

import * as fs from "fs";
import { readFile } from "fs/promises";
import * as yaml from "yaml";

import { Logger } from "@nestjs/common";
import { OpenAPIObject } from "@nestjs/swagger";

/**
 * Recursively sorts the keys of an object or elements of an array.
 * This is used to ensure a deterministic order when stringifying the OpenAPI document to YAML,
 * which helps in preventing unnecessary diffs in version control.
 *
 * @param obj The object or array to sort.
 * @returns The sorted object or array.
 */
function sortObject(obj: any): any {
  if (Array.isArray(obj)) return obj.map(sortObject);

  if (obj && typeof obj === "object") {
    return Object.keys(obj)
      .sort()
      .reduce((acc, key) => {
        acc[key] = sortObject(obj[key]);
        return acc;
      }, {} as any);
  }

  return obj;
}

/**
 * Generates a `swagger.yaml` file from a given OpenAPI document object.
 *
 * It first sorts the document to ensure a consistent output. Then, it compares the new document
 * with the existing `swagger.yaml` file (if any). The file is only written if the content has changed
 * or if the `force` parameter is set to `true`.
 *
 * @param {OpenAPIObject} document The OpenAPI document object, typically generated by NestJS/Swagger.
 * @param {boolean} [force=false] If true, the `swagger.yaml` file will be written even if no changes are detected.
 * @returns {Promise<void>} A promise that resolves when the operation is complete.
 */
export async function generateApi(document: OpenAPIObject, force = false): Promise<void> {
  const logger = new Logger("API GENERATOR");

  const normalized = sortObject(document);
  const newYaml = yaml.stringify(normalized);

  let savedNormalized: any = null;

  try {
    const buffer = await readFile("./swagger.yaml");
    savedNormalized = sortObject(yaml.parse(buffer.toString()));
  } catch {
    logger.verbose("swagger.yaml not found, creating new one...");
  }

  if (savedNormalized && JSON.stringify(savedNormalized) === JSON.stringify(normalized) && !force) {
    return;
  }

  fs.writeFileSync("./swagger.yaml", newYaml);
}
